# Generated by Django 4.1.5 on 2023-12-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"verbose_name": "notes", "verbose_name_plural": "notes"},
        ),
    ]
