# Generated by Django 4.1.5 on 2023-12-18 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0002_alter_notes_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"ordering": ("-created", "-updated")},
        ),
        migrations.AddField(
            model_name="notes",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notes",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
