# Generated by Django 4.2.1 on 2023-12-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0004_homework"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homework",
            options={"ordering": ("-due", "-created")},
        ),
        migrations.RemoveField(
            model_name="homework",
            name="updated",
        ),
        migrations.AlterField(
            model_name="homework",
            name="due",
            field=models.DateTimeField(),
        ),
    ]
