# Generated by Django 4.2.1 on 2023-12-20 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0007_todo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "todo", "verbose_name_plural": "todos"},
        ),
        migrations.AddField(
            model_name="todo",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
