# Generated by Django 4.2.1 on 2023-12-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0009_alter_todo_date_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "Todo", "verbose_name_plural": "Todos"},
        ),
    ]
