# Generated by Django 4.2.1 on 2023-12-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0010_alter_todo_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="date_created",
            new_name="created",
        ),
    ]
