# Generated by Django 4.2.1 on 2023-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0011_rename_date_created_todo_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
