# Generated by Django 4.2.1 on 2023-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0012_alter_todo_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created",
            field=models.DateTimeField(),
        ),
    ]
