# Generated by Django 4.2.1 on 2023-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0013_alter_homework_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="tasks",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
