# Generated by Django 4.2.1 on 2023-12-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0014_alter_todo_created_alter_todo_tasks_alter_todo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
