# Generated by Django 4.2.1 on 2023-12-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboardApp", "0015_alter_todo_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
